#!/bin/bash


## Get Battery 
BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)
BATSTATUS="$(cat /sys/class/power_supply/${BAT}/status)"
BATVAL="$(cat /sys/class/power_supply/${BAT}/capacity)"
BATICON=""

if [[ "$BATSTATUS" == "Discharging" ]];then
  if [ "$BATVAL" -gt 90 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 80 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 70 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 60 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 50 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 40 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 30 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 20 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 10 ];then
    BATICON=""
  elif [ "$BATVAL" -gt 0 ];then
    BATICON=""
  fi
 else
  BATICON=""
fi

echo "$BATICON $BATVAL%"