#!/bin/bash


up() {
  brightnessctl s 10%+
}

down() {
  brightnessctl s 10%-
}

get() {
  DEVICE=$(brightnessctl -l | grep "class 'backlight'" | awk '{print $2}' | tr -d "'")
  echo  $(brightnessctl -m -d $DEVICE | awk -F, '{print substr($4, 0, length($4)-1)}')%
}



if [[ "$1" == "--up" ]];then
  up
elif [[ "$1" == "--down" ]];then
  down
elif [[ "$1" == "--get" ]];then
  get
fi
