#!/bin/bash

i3lock \
-i $HOME/.config/background \
--screen 1 \
--clock \
--indicator \
--ring-color "#1e1e1e66" \
--line-color "#00000000" \
--inside-color "#dfdfdf33" \
--separator-color "#ffffff00" \
--time-str "%R" \
--date-str "%A, %d-%m-%Y" \

