#!/bin/bash


BLANK="#00000000"
FG="#ebdbb2ff"
BG="#1d2021ff"
RING="#282828ff"


i3lock \
--screen 1 \
--clock \
--indicator \
--color $BG \
--ring-color $RING \
--line-color $BLANK \
--inside-color $BLANK \
--separator-color $BLANK \
--time-str "%R" \
--date-str "%d-%m-%Y" \
--time-color $FG \
--date-color $FG \
--radius 80
